# Generated by Django 3.2.12 on 2022-03-30 16:16

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_auto_20220325_2330'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recharge', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Recharge',
            new_name='Purchase',
        ),
    ]
