# Generated by Django 3.2 on 2022-06-19 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_user_country_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='store_setup',
        ),
    ]
