# Generated by Django 3.2.12 on 2022-03-30 13:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('savings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal_title', models.CharField(blank=True, max_length=255, null=True)),
                ('goal_amount', models.BigIntegerField(default=0)),
                ('breakage_charges', models.IntegerField(default=0)),
                ('breaked', models.BooleanField(default=False)),
                ('status', models.CharField(blank=True, choices=[('breaked', 'breaked'), ('initiated', 'initiated'), ('processing', 'processing'), ('completed', 'completed')], max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SavingsAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_balance', models.BigIntegerField(default=0)),
                ('saving', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='savings.saving')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GoalTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(blank=True, choices=[('submited', 'submited'), ('on_process', 'on_process'), ('success', 'success'), ('failure', 'failure')], max_length=255, null=True)),
                ('transaction_amount', models.BigIntegerField(blank=True, null=True)),
                ('transaction_type', models.CharField(blank=True, choices=[('transfer', 'transfer'), ('request', 'request'), ('recieved', 'recieved'), ('deposit', 'deposit'), ('withdraw', 'withdraw')], max_length=255, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('goal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='savings.goal')),
            ],
        ),
        migrations.AddField(
            model_name='goal',
            name='savings_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='savings.savingsaccount'),
        ),
    ]
