# Generated by Django 3.2.12 on 2022-12-30 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_remove_jsonserializer_api_jsonserializer_api'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jsonserializer',
            name='api',
            field=models.ManyToManyField(blank=True, related_name='serializer', to='website.Api'),
        ),
    ]
