# Generated by Django 3.2.12 on 2022-12-30 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_auto_20221230_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='api',
            name='headers',
            field=models.TextField(blank=True, null=True),
        ),
    ]
