# Generated by Django 3.2.12 on 2023-01-03 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_api_headers'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomFuction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('headers', models.TextField(blank=True, null=True)),
                ('content', models.TextField(blank=True, max_length=2500, null=True)),
                ('api', models.ManyToManyField(blank=True, related_name='function', to='website.Api')),
            ],
        ),
    ]
