# Generated by Django 3.2.12 on 2022-03-31 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_provider'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='finance',
            name='service',
        ),
        migrations.DeleteModel(
            name='Provider',
        ),
        migrations.DeleteModel(
            name='Finance',
        ),
    ]
