# Generated by Django 3.2.8 on 2022-04-15 14:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_id',
            field=models.CharField(default=uuid.UUID('5f473f70-5874-46dd-84b9-2d51d31e62b7'), max_length=255, unique=True),
        ),
    ]
