# Generated by Django 3.2.12 on 2022-03-24 22:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_id',
            field=models.CharField(default=uuid.UUID('1aea5a8c-a4ee-4671-a896-469ed129f36d'), max_length=255, unique=True),
        ),
    ]
