# Generated by Django 3.2.8 on 2022-04-15 14:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_alter_payment_payment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_id',
            field=models.CharField(default=uuid.UUID('dafda3db-10f2-4738-9c40-61ff5cab60a9'), max_length=255, unique=True),
        ),
    ]
