# Generated by Django 3.2.12 on 2022-03-24 22:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_alter_payment_payment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_id',
            field=models.CharField(default=uuid.UUID('5cc18c47-3860-4f6f-8dcc-0e54ffda654d'), max_length=255, unique=True),
        ),
    ]
