# Generated by Django 3.2.12 on 2022-03-25 12:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_alter_payment_payment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='reference_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_id',
            field=models.CharField(default=uuid.UUID('045ee272-92cd-4463-a58c-0352c51071f0'), max_length=255, unique=True),
        ),
    ]
