# Generated by Django 3.2.8 on 2022-04-15 15:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_alter_payment_payment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_id',
            field=models.CharField(default=uuid.UUID('e9a2dd7e-785d-4f66-a856-9ace3a317511'), max_length=255, unique=True),
        ),
    ]
