# Generated by Django 3.2.12 on 2022-03-25 13:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_auto_20220325_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_id',
            field=models.CharField(default=uuid.UUID('73ba3357-d661-44ad-9726-cdd54d43cf7e'), max_length=255, unique=True),
        ),
    ]
