# Generated by Django 3.2.12 on 2022-04-20 11:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_alter_payment_payment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_id',
            field=models.CharField(default=uuid.UUID('fb0edf7d-5076-4e82-b12b-364284765196'), max_length=255, unique=True),
        ),
    ]
