# Generated by Django 3.2.12 on 2022-03-25 13:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_alter_payment_payment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_id',
            field=models.CharField(default=uuid.UUID('4f0723b4-aa43-46bc-883c-e7d58351143d'), max_length=255, unique=True),
        ),
    ]
