# Generated by Django 3.2.12 on 2022-04-20 11:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_alter_payment_payment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_id',
            field=models.CharField(default=uuid.UUID('4fa5b006-d4ba-46c5-8a07-0ab44305fcfe'), max_length=255, unique=True),
        ),
    ]
