# Generated by Django 3.2.12 on 2022-03-25 15:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0006_alter_payment_payment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_id',
            field=models.CharField(default=uuid.UUID('721708f2-acb5-4e7c-a224-dce7beb31a69'), max_length=255, unique=True),
        ),
    ]
