# Generated by Django 3.2.12 on 2022-04-20 12:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0006_alter_payment_payment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_id',
            field=models.CharField(default=uuid.UUID('a9f7f1e8-d725-4945-8de2-bc3d2beb3622'), max_length=255, unique=True),
        ),
    ]
