# Generated by Django 3.2.12 on 2022-04-20 13:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0007_alter_payment_payment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_id',
            field=models.CharField(default=uuid.UUID('72cdf753-3c0e-474d-875d-cebdc6e76319'), max_length=255, unique=True),
        ),
    ]
