# Generated by Django 3.2.12 on 2022-03-25 18:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0007_alter_payment_payment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_id',
            field=models.CharField(default=uuid.UUID('18d9e2e8-8b42-46cb-9d2f-1f53f1b1c486'), max_length=255, unique=True),
        ),
    ]
