# Generated by Django 3.2.12 on 2022-03-25 20:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0008_alter_payment_payment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_id',
            field=models.CharField(default=uuid.UUID('70a9f496-ecab-41a8-8db0-3fc5dfe52231'), max_length=255, unique=True),
        ),
    ]
