# Generated by Django 3.2.8 on 2022-04-26 16:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0009_alter_payment_payment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_id',
            field=models.CharField(default=uuid.UUID('3da6759e-b9a0-4096-8e18-21bad317f679'), max_length=255, unique=True),
        ),
    ]
