# Generated by Django 3.2.12 on 2022-03-25 20:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0009_alter_payment_payment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_id',
            field=models.CharField(default=uuid.UUID('2bd6c3af-c96a-417f-bdfc-aca3518bce04'), max_length=255, unique=True),
        ),
    ]
