# Generated by Django 3.2.8 on 2022-04-26 17:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0010_alter_payment_payment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_id',
            field=models.CharField(default=uuid.UUID('e3ba34f1-f503-4983-9c1c-de28a95da689'), max_length=255, unique=True),
        ),
    ]
