# Generated by Django 3.2.12 on 2022-03-25 20:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0010_alter_payment_payment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_id',
            field=models.CharField(default=uuid.UUID('38e9b95c-3313-4da5-bbec-767738053078'), max_length=255, unique=True),
        ),
    ]
