# Generated by Django 3.2.8 on 2022-04-26 18:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0011_alter_payment_payment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_id',
            field=models.CharField(default=uuid.UUID('2b44d0e1-a6fc-4fdf-b034-30c8c69320db'), max_length=255, unique=True),
        ),
    ]
