# Generated by Django 3.2.12 on 2022-03-25 20:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0011_alter_payment_payment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_id',
            field=models.CharField(default=uuid.UUID('a3e2afff-cae4-4f58-822b-893b2cce65b5'), max_length=255, unique=True),
        ),
    ]
