# Generated by Django 3.2.8 on 2022-04-26 19:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0012_alter_payment_payment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_id',
            field=models.CharField(default=uuid.UUID('90395d43-653b-42af-9e84-ec85ae6c9e73'), max_length=255, unique=True),
        ),
    ]
