# Generated by Django 3.2.12 on 2022-03-25 20:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0012_alter_payment_payment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_id',
            field=models.CharField(default=uuid.UUID('65c3d37c-5784-4705-ab76-0cb7c891c020'), max_length=255, unique=True),
        ),
    ]
