# Generated by Django 3.2.8 on 2022-04-26 20:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0013_alter_payment_payment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_id',
            field=models.CharField(default=uuid.UUID('99bdfa43-5f88-487e-a89d-94000d92f952'), max_length=255, unique=True),
        ),
    ]
