# Generated by Django 3.2.12 on 2022-03-30 13:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0014_alter_payment_payment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_id',
            field=models.CharField(default=uuid.UUID('cb481e8c-bccc-4e63-abcf-23a90c5564fd'), max_length=255, unique=True),
        ),
    ]
