# Generated by Django 3.2.8 on 2022-04-26 20:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0014_alter_payment_payment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_id',
            field=models.CharField(default=uuid.UUID('7a22813f-99d3-4a7c-b5e7-5e0c52f20a03'), max_length=255, unique=True),
        ),
    ]
