# Generated by Django 3.2.8 on 2022-05-01 22:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0015_alter_payment_payment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_id',
            field=models.CharField(default=uuid.UUID('2a28d647-749f-49b7-b340-7f3f336e9b7a'), max_length=255, unique=True),
        ),
    ]
