# Generated by Django 3.2.12 on 2022-03-30 13:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0015_alter_payment_payment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_id',
            field=models.CharField(default=uuid.UUID('81ae38f1-a14e-4627-b112-7d293505edbb'), max_length=255, unique=True),
        ),
    ]
