# Generated by Django 3.2.12 on 2022-03-30 13:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0016_alter_payment_payment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_id',
            field=models.CharField(default=uuid.UUID('17b24f8f-9721-4311-9cea-2f4fd826a08b'), max_length=255, unique=True),
        ),
    ]
