# Generated by Django 3.2.8 on 2022-05-01 22:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0016_alter_payment_payment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_id',
            field=models.CharField(default=uuid.UUID('633a217d-b9dc-4ea4-8a87-c7fd13ed39a5'), max_length=255, unique=True),
        ),
    ]
