# Generated by Django 3.2.12 on 2022-03-30 13:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0017_alter_payment_payment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_id',
            field=models.CharField(default=uuid.UUID('22053543-5b8c-4d8a-8420-a36dd75729d1'), max_length=255, unique=True),
        ),
    ]
