# Generated by Django 3.2.8 on 2022-05-03 14:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0017_alter_payment_payment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_id',
            field=models.CharField(default=uuid.UUID('95a24d5a-f570-4e25-8801-2bba05c75e3b'), max_length=255, unique=True),
        ),
    ]
