# Generated by Django 3.2.12 on 2022-03-30 14:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0018_alter_payment_payment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_id',
            field=models.CharField(default=uuid.UUID('615de539-b0b8-4ca5-bd12-9159f64595c4'), max_length=255, unique=True),
        ),
    ]
