# Generated by Django 3.2.8 on 2022-05-09 21:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0019_alter_payment_payment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_id',
            field=models.CharField(default=uuid.UUID('6c827992-fd88-4153-a163-3118e0ef9d55'), max_length=255, unique=True),
        ),
    ]
