# Generated by Django 3.2.12 on 2022-03-30 14:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0019_alter_payment_payment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_id',
            field=models.CharField(default=uuid.UUID('a2e7826f-eb02-45fe-904c-d3e3de31a8e5'), max_length=255, unique=True),
        ),
    ]
