# Generated by Django 3.2.8 on 2022-05-10 13:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0020_alter_payment_payment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_id',
            field=models.CharField(default=uuid.UUID('0b9c4e6c-d653-4dba-af23-12e61a039efd'), max_length=255, unique=True),
        ),
    ]
