# Generated by Django 3.2.8 on 2022-05-13 17:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0021_alter_payment_payment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_id',
            field=models.CharField(default=uuid.UUID('969a236c-8e90-4bbd-b0e8-27563f774454'), max_length=255, unique=True),
        ),
    ]
