# Generated by Django 3.2.12 on 2022-03-30 15:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0021_alter_payment_payment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_id',
            field=models.CharField(default=uuid.UUID('eace25ac-762f-4c9f-bfb9-ed4a43a342ed'), max_length=255, unique=True),
        ),
    ]
