# Generated by Django 3.2.8 on 2022-05-13 17:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0022_alter_payment_payment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_id',
            field=models.CharField(default=uuid.UUID('6589674a-7bee-4e0d-b94c-48f031eb5949'), max_length=255, unique=True),
        ),
    ]
