# Generated by Django 3.2.12 on 2022-03-30 16:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0023_alter_payment_payment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_id',
            field=models.CharField(default=uuid.UUID('ef91a78c-5804-44bd-b71e-62fa3acbfb7a'), max_length=255, unique=True),
        ),
    ]
