# Generated by Django 3.2.8 on 2022-05-13 20:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0024_alter_payment_payment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_id',
            field=models.CharField(default=uuid.UUID('1c931d49-ff28-4df9-89e9-6c0f624940e6'), max_length=255, unique=True),
        ),
    ]
