# Generated by Django 3.2.12 on 2022-03-30 16:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0024_alter_payment_payment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_id',
            field=models.CharField(default=uuid.UUID('b3daf962-a4aa-420e-9cc2-772b02393cc8'), max_length=255, unique=True),
        ),
    ]
