# Generated by Django 3.2.12 on 2022-03-30 16:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0025_alter_payment_payment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_id',
            field=models.CharField(default=uuid.UUID('2fa70671-f423-4f52-abd4-29a2593a9d74'), max_length=255, unique=True),
        ),
    ]
