# Generated by Django 3.2.8 on 2022-05-16 13:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0026_alter_payment_payment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_id',
            field=models.CharField(default=uuid.UUID('9de49212-663d-4598-8843-9c21f0c5b440'), max_length=255, unique=True),
        ),
    ]
