# Generated by Django 3.2.12 on 2022-03-30 19:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0027_alter_payment_payment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_id',
            field=models.CharField(default=uuid.UUID('03c4621d-d482-42f2-b3ba-56b19cfc53d6'), max_length=255, unique=True),
        ),
    ]
