# Generated by Django 3.2.12 on 2022-03-31 12:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0028_alter_payment_payment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_id',
            field=models.CharField(default=uuid.UUID('dbb97e58-7192-4fd4-a8ab-c705e6d21ca0'), max_length=255, unique=True),
        ),
    ]
