# Generated by Django 3.2.8 on 2022-05-16 15:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0028_alter_payment_payment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_id',
            field=models.CharField(default=uuid.UUID('1331d85f-b624-420d-9180-1eb74bde194e'), max_length=255, unique=True),
        ),
    ]
