# Generated by Django 3.2.8 on 2022-05-16 15:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0029_alter_payment_payment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_id',
            field=models.CharField(default=uuid.UUID('75f95110-164e-4e17-98b6-a7b8a35efcbc'), max_length=255, unique=True),
        ),
    ]
