# Generated by Django 3.2.12 on 2022-03-31 18:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0030_alter_payment_payment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_id',
            field=models.CharField(default=uuid.UUID('b3368a28-9fd7-40e2-b07b-f3fa5741317c'), max_length=255, unique=True),
        ),
    ]
