# Generated by Django 3.2.8 on 2022-05-16 15:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0030_alter_payment_payment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_id',
            field=models.CharField(default=uuid.UUID('98d9f244-0b1d-48f0-a86b-93f2b752a911'), max_length=255, unique=True),
        ),
    ]
