# Generated by Django 3.2.8 on 2022-05-16 15:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0031_alter_payment_payment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_id',
            field=models.CharField(default=uuid.UUID('0738ca9d-0ca0-436b-a73a-7a40cafb04b4'), max_length=255, unique=True),
        ),
    ]
