# Generated by Django 3.2.8 on 2022-05-16 16:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0032_alter_payment_payment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_id',
            field=models.CharField(default=uuid.UUID('f1e7d5f1-c6ef-4c90-ba46-75f7614efc8e'), max_length=255, unique=True),
        ),
    ]
