# Generated by Django 3.2.12 on 2022-03-31 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='X',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_type', models.CharField(blank=True, choices=[('buy', 'buy'), ('sell', 'sell')], max_length=255, null=True)),
            ],
        ),
    ]
