# Generated by Django 3.2.8 on 2022-04-26 16:59

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('veregood_service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='first_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='nick_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vendorservice',
            name='description',
            field=models.TextField(blank=True, max_length=2500, null=True),
        ),
        migrations.AddField(
            model_name='vendorservice',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='vendorservice',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='vendorservice',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='vendor/profile/images/'),
        ),
        migrations.AddField(
            model_name='vendorservice',
            name='service_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='veregood_service.veregoodservice'),
        ),
        migrations.AddField(
            model_name='vendorservice',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='veregood_service.vendor'),
        ),
        migrations.AddField(
            model_name='veregoodservice',
            name='service_icon',
            field=models.ImageField(blank=True, null=True, upload_to='veregood_service/icon'),
        ),
        migrations.AddField(
            model_name='veregoodservice',
            name='service_image',
            field=models.ImageField(blank=True, null=True, upload_to='veregood_service/images'),
        ),
        migrations.AddField(
            model_name='veregoodservice',
            name='service_name',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='vendor/service/images/')),
                ('vendor_service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='veregood_service.vendorservice')),
            ],
        ),
    ]
