# Generated by Django 3.2.8 on 2022-04-26 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('veregood_service', '0002_auto_20220426_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorservice',
            name='rating',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(blank=True, max_length=255, null=True)),
                ('stars', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True, max_length=2500, null=True)),
                ('vendor_service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='veregood_service.vendorservice')),
            ],
        ),
    ]
