# Generated by Django 3.2.8 on 2022-04-26 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veregood_service', '0003_auto_20220426_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
