# Generated by Django 3.2.8 on 2022-04-26 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('veregood_service', '0005_auto_20220426_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='vendor_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='portfolio', to='veregood_service.vendorservice'),
        ),
        migrations.AlterField(
            model_name='review',
            name='vendor_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='review', to='veregood_service.vendorservice'),
        ),
    ]
