# Generated by Django 3.2.8 on 2022-05-03 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veregood_service', '0008_alter_vendorservice_charge'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='proof_one',
            field=models.ImageField(blank=True, null=True, upload_to='vendor/proof1/'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='proof_two',
            field=models.ImageField(blank=True, null=True, upload_to='vendor/proof2/'),
        ),
    ]
