# Generated by Django 3.2.8 on 2022-05-16 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('veregood_service', '0009_auto_20220503_1400'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendorservice',
            name='vendor',
        ),
        migrations.DeleteModel(
            name='Vendor',
        ),
    ]
