# Generated by Django 3.2.8 on 2022-05-16 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_vendor'),
        ('veregood_service', '0010_auto_20220516_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorservice',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.vendor'),
        ),
    ]
