# Generated by Django 3.2.12 on 2022-03-23 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to='images/service'),
        ),
        migrations.AddField(
            model_name='service',
            name='slug',
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='service',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
