# Generated by Django 3.2.12 on 2022-03-25 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_dth_mobilerecharge'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DTH',
        ),
        migrations.DeleteModel(
            name='Finance',
        ),
        migrations.DeleteModel(
            name='Health',
        ),
        migrations.DeleteModel(
            name='MobileRecharge',
        ),
    ]
