# Generated by Django 3.2.12 on 2022-03-30 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_recharge', '0002_auto_20220330_1924'),
    ]

    operations = [
        migrations.AddField(
            model_name='recharge',
            name='mobile_recharge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mobile_recharge.mobilerecharge'),
        ),
    ]
