# Generated by Django 3.2.12 on 2022-03-30 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_recharge', '0004_auto_20220330_2113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='operator',
        ),
        migrations.RemoveField(
            model_name='recharge',
            name='operator',
        ),
        migrations.RemoveField(
            model_name='recharge',
            name='package',
        ),
        migrations.RemoveField(
            model_name='recharge',
            name='service',
        ),
        migrations.RemoveField(
            model_name='recharge',
            name='user',
        ),
        migrations.DeleteModel(
            name='Operator',
        ),
        migrations.DeleteModel(
            name='Package',
        ),
        migrations.DeleteModel(
            name='Recharge',
        ),
    ]
