# Generated by Django 3.2.12 on 2022-03-25 22:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='wallet_id',
            field=models.UUIDField(default=uuid.UUID('0b9d906e-ddf1-44ec-8895-e23b05cf3c67'), unique=True),
        ),
    ]
