# Generated by Django 3.2.8 on 2022-04-15 14:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='wallet_id',
            field=models.UUIDField(default=uuid.UUID('7762d4a5-cbdd-425b-bcbc-c746f7cbf65c'), unique=True),
        ),
    ]
