# Generated by Django 3.2.8 on 2022-04-15 15:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_alter_wallet_wallet_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='wallet_id',
            field=models.UUIDField(default=uuid.UUID('dcbc372d-301e-41db-9129-46991db770b4'), unique=True),
        ),
    ]
