# Generated by Django 3.2.12 on 2022-03-30 13:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_alter_wallet_wallet_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='wallet_id',
            field=models.UUIDField(default=uuid.UUID('cdb9ca0c-48b1-4e1a-b843-dffd41d1c2c2'), unique=True),
        ),
    ]
