# Generated by Django 3.2.12 on 2022-04-20 11:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0004_alter_wallet_wallet_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='wallet_id',
            field=models.UUIDField(default=uuid.UUID('0c402ee8-f1e5-4769-85b4-a4f29299730d'), unique=True),
        ),
    ]
