# Generated by Django 3.2.12 on 2022-03-30 13:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0004_alter_wallet_wallet_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='wallet_id',
            field=models.UUIDField(default=uuid.UUID('e6d22a60-e695-467a-96e9-8f4e76465844'), unique=True),
        ),
    ]
