# Generated by Django 3.2.12 on 2022-03-30 13:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0005_alter_wallet_wallet_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='wallet_id',
            field=models.UUIDField(default=uuid.UUID('3d8b0cb9-cd84-4448-890c-134122671806'), unique=True),
        ),
    ]
