# Generated by Django 3.2.12 on 2022-04-20 12:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0006_alter_wallet_wallet_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='wallet_id',
            field=models.UUIDField(default=uuid.UUID('ff1e450b-7d70-4975-8f46-b00bd84f0224'), unique=True),
        ),
    ]
