# Generated by Django 3.2.12 on 2022-03-30 14:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0006_alter_wallet_wallet_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='wallet_id',
            field=models.UUIDField(default=uuid.UUID('80dcc9b8-a102-4a90-93ee-85e1450ba87a'), unique=True),
        ),
    ]
