# Generated by Django 3.2.12 on 2022-04-20 13:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0007_alter_wallet_wallet_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='wallet_id',
            field=models.UUIDField(default=uuid.UUID('5a997b3c-7556-4721-bd9f-c24d2fe65dfb'), unique=True),
        ),
    ]
