# Generated by Django 3.2.12 on 2022-03-30 14:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0007_alter_wallet_wallet_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='wallet_id',
            field=models.UUIDField(default=uuid.UUID('4fc0b4c7-553d-432d-b98d-52f0d69af67e'), unique=True),
        ),
    ]
