# Generated by Django 3.2.8 on 2022-04-26 12:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0008_alter_wallet_wallet_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='wallet_id',
            field=models.UUIDField(default=uuid.UUID('341ec208-3b3b-460c-b82b-b120cb6a68e1'), unique=True),
        ),
    ]
