# Generated by Django 3.2.12 on 2022-03-30 14:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0008_alter_wallet_wallet_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='wallet_id',
            field=models.UUIDField(default=uuid.UUID('0c65a662-064c-4a29-ac1d-b024d4e21291'), unique=True),
        ),
    ]
