# Generated by Django 3.2.12 on 2022-03-30 15:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0009_alter_wallet_wallet_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='wallet_id',
            field=models.UUIDField(default=uuid.UUID('3132838e-6a2b-4ff9-9d90-5aa8c6d34d00'), unique=True),
        ),
    ]
