# Generated by Django 3.2.8 on 2022-04-26 16:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0009_alter_wallet_wallet_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='wallet_id',
            field=models.UUIDField(default=uuid.UUID('b30353a0-bea2-4690-a868-4691171d84b8'), unique=True),
        ),
    ]
