# Generated by Django 3.2.8 on 2022-04-26 17:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0010_alter_wallet_wallet_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='wallet_id',
            field=models.UUIDField(default=uuid.UUID('53e953e8-b42e-4def-ba51-aa50860debe3'), unique=True),
        ),
    ]
