# Generated by Django 3.2.12 on 2022-03-30 15:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0010_alter_wallet_wallet_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='wallet_id',
            field=models.UUIDField(default=uuid.UUID('0c788248-7c00-4215-ac26-fe5ad1b24c0b'), unique=True),
        ),
    ]
