# Generated by Django 3.2.12 on 2022-03-30 16:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0011_alter_wallet_wallet_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='wallet_id',
            field=models.UUIDField(default=uuid.UUID('bfd5e548-a793-40ab-86c4-5677bc12cd90'), unique=True),
        ),
    ]
