# Generated by Django 3.2.8 on 2022-04-26 18:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0011_alter_wallet_wallet_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='wallet_id',
            field=models.UUIDField(default=uuid.UUID('dbae9af1-80e4-48c5-98d4-036878239efd'), unique=True),
        ),
    ]
