# Generated by Django 3.2.8 on 2022-04-26 19:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0012_alter_wallet_wallet_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='wallet_id',
            field=models.UUIDField(default=uuid.UUID('a6f25793-b771-4931-b6b6-2519fff1e963'), unique=True),
        ),
    ]
