# Generated by Django 3.2.12 on 2022-03-30 16:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0012_alter_wallet_wallet_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='wallet_id',
            field=models.UUIDField(default=uuid.UUID('a0c500c1-6e5a-463b-8b10-92a35b4c9c87'), unique=True),
        ),
    ]
