# Generated by Django 3.2.8 on 2022-04-26 20:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0013_alter_wallet_wallet_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='wallet_id',
            field=models.UUIDField(default=uuid.UUID('965c56a4-dfef-4153-b7d3-53bca01f15ec'), unique=True),
        ),
    ]
