# Generated by Django 3.2.8 on 2022-04-26 20:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0014_alter_wallet_wallet_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='wallet_id',
            field=models.UUIDField(default=uuid.UUID('e9e03c7e-4613-4570-b190-2d2bf6ad8333'), unique=True),
        ),
    ]
