# Generated by Django 3.2.8 on 2022-05-01 22:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0015_alter_wallet_wallet_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='wallet_id',
            field=models.UUIDField(default=uuid.UUID('0e2f4939-d964-4342-a957-ece7d569dfd6'), unique=True),
        ),
    ]
