# Generated by Django 3.2.12 on 2022-03-30 19:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0015_alter_wallet_wallet_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='wallet_id',
            field=models.UUIDField(default=uuid.UUID('eb04bdd1-cc1b-4edb-a582-46d9f914fec8'), unique=True),
        ),
    ]
