# Generated by Django 3.2.8 on 2022-05-01 22:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0016_alter_wallet_wallet_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='wallet_id',
            field=models.UUIDField(default=uuid.UUID('818bc456-6a61-4eaa-a87a-714bb8afbe1b'), unique=True),
        ),
    ]
