# Generated by Django 3.2.12 on 2022-03-31 12:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0016_alter_wallet_wallet_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='wallet_id',
            field=models.UUIDField(default=uuid.UUID('93a09334-e807-4d69-9421-88342aa33653'), unique=True),
        ),
    ]
