# Generated by Django 3.2.8 on 2022-05-03 14:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0017_alter_wallet_wallet_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='wallet_id',
            field=models.UUIDField(default=uuid.UUID('4974f95d-f047-4cff-81da-342411ef882d'), unique=True),
        ),
    ]
