# Generated by Django 3.2.12 on 2022-03-31 12:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0017_alter_wallet_wallet_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='wallet_id',
            field=models.UUIDField(default=uuid.UUID('9d11e3ff-b80f-4a11-9014-15d10928e71d'), unique=True),
        ),
    ]
