# Generated by Django 3.2.12 on 2022-03-31 18:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0018_alter_wallet_wallet_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='wallet_id',
            field=models.UUIDField(default=uuid.UUID('c266d580-ff05-4c63-b55d-4852a2c854b3'), unique=True),
        ),
    ]
