# Generated by Django 3.2.8 on 2022-05-10 13:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0020_alter_wallet_wallet_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='wallet_id',
            field=models.UUIDField(default=uuid.UUID('13ea62b5-5b32-4437-9956-a35107899d05'), unique=True),
        ),
    ]
