# Generated by Django 3.2.8 on 2022-05-13 17:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0021_alter_wallet_wallet_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='wallet_id',
            field=models.UUIDField(default=uuid.UUID('19128fc0-4e61-4094-a3b5-5747f0486afa'), unique=True),
        ),
    ]
