# Generated by Django 3.2.8 on 2022-05-13 17:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0023_alter_wallet_wallet_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='wallet_id',
            field=models.UUIDField(default=uuid.UUID('da6dbc0c-91fe-4b03-a909-46a9490cc69c'), unique=True),
        ),
    ]
