# Generated by Django 3.2.8 on 2022-05-13 20:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0024_alter_wallet_wallet_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='wallet_id',
            field=models.UUIDField(default=uuid.UUID('d565f76d-9d04-4b5a-88fb-cd055ebe1d32'), unique=True),
        ),
    ]
