# Generated by Django 3.2.8 on 2022-05-16 13:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0026_alter_wallet_wallet_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='wallet_id',
            field=models.UUIDField(default=uuid.UUID('47926245-7957-49f5-9771-23e0cc33884e'), unique=True),
        ),
    ]
