# Generated by Django 3.2.8 on 2022-05-16 13:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0027_alter_wallet_wallet_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='wallet_id',
            field=models.UUIDField(default=uuid.UUID('1850d594-f0ac-4f88-a47c-46dd6a0f2c25'), unique=True),
        ),
    ]
