# Generated by Django 3.2.8 on 2022-05-16 15:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0028_alter_wallet_wallet_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='wallet_id',
            field=models.UUIDField(default=uuid.UUID('988efa9b-ce7e-4933-9902-2f11edb2a63e'), unique=True),
        ),
    ]
