# Generated by Django 3.2.8 on 2022-05-16 15:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0029_alter_wallet_wallet_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='wallet_id',
            field=models.UUIDField(default=uuid.UUID('d1a4e0b9-2d7a-4934-b1b8-5e6568c5b10a'), unique=True),
        ),
    ]
