# Generated by Django 3.2.8 on 2022-04-15 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_number', models.CharField(blank=True, max_length=255, null=True)),
                ('bill_type', models.CharField(blank=True, choices=[('electricity', 'electricity'), ('water', 'water'), ('postpaid', 'postpaid'), ('others', 'others')], max_length=255, null=True)),
                ('mobile_number', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('country', models.CharField(blank=True, max_length=255, null=True)),
                ('state', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('payment_amount', models.BigIntegerField(default=0)),
                ('payment_status', models.CharField(blank=True, choices=[('success', 'success'), ('failure', 'failure'), ('processing', 'processing')], max_length=255, null=True)),
                ('recharge_status', models.CharField(blank=True, choices=[('success', 'success'), ('failure', 'failure'), ('processing', 'processing')], max_length=255, null=True)),
                ('completed', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
