# Generated by Django 3.2.8 on 2022-04-15 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crytpo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('image_url', models.ImageField(blank=True, null=True, upload_to='crypto/logo/images')),
                ('wallet_address', models.TextField(blank=True, max_length=1500, null=True)),
            ],
            options={
                'verbose_name_plural': 'Cryto',
            },
        ),
        migrations.CreateModel(
            name='NOTIFICATION_PROVIDER',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('key', models.TextField(max_length=1500)),
                ('secrect', models.TextField(max_length=1500)),
                ('web_url', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Notification',
            },
        ),
        migrations.CreateModel(
            name='PAYMENTGATEWAY',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('key', models.TextField(max_length=1500)),
                ('secrect', models.TextField(max_length=1500)),
                ('web_url', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Payment Gateway',
            },
        ),
        migrations.CreateModel(
            name='PAYMENTPARTNER',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('key', models.TextField(max_length=1500)),
                ('secrect', models.TextField(max_length=1500)),
                ('web_url', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Payout',
            },
        ),
        migrations.CreateModel(
            name='SMSGATEWAY',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('key', models.TextField(max_length=1500)),
                ('secrect', models.TextField(max_length=1500)),
                ('web_url', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Sms Gateway',
            },
        ),
    ]
