# Generated by Django 3.2.12 on 2022-03-24 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0003_smsgateway'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrytpoAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('image_url', models.ImageField(upload_to='crypto/logo/images')),
                ('wallet_address', models.TextField(blank=True, max_length=1500, null=True)),
            ],
        ),
    ]
