# Generated by Django 3.2.12 on 2022-03-24 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0004_crytpoaccount'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CrytpoAccount',
            new_name='Crytpo',
        ),
    ]
