# Generated by Django 3.2.12 on 2022-03-24 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0005_rename_crytpoaccount_crytpo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crytpo',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to='crypto/logo/images'),
        ),
    ]
