# Generated by Django 3.2.12 on 2022-03-24 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0006_alter_crytpo_image_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='NOTIFICATION_PROVIDER',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('key', models.TextField(max_length=1500)),
                ('secrect', models.TextField(max_length=1500)),
                ('web_url', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
