# Generated by Django 3.2.12 on 2022-03-25 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0007_notification_provider'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='crytpo',
            options={'verbose_name_plural': 'Cryto'},
        ),
        migrations.AlterModelOptions(
            name='notification_provider',
            options={'verbose_name_plural': 'Notification'},
        ),
        migrations.AlterModelOptions(
            name='paymentgateway',
            options={'verbose_name_plural': 'Payment Gateway'},
        ),
        migrations.AlterModelOptions(
            name='paymentpartner',
            options={'verbose_name_plural': 'Payout'},
        ),
        migrations.AlterModelOptions(
            name='smsgateway',
            options={'verbose_name_plural': 'Sms Gateway'},
        ),
    ]
