# Generated by Django 3.2 on 2022-06-22 10:00

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields
import tinymce.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='veregood/banner/image/')),
                ('is_active', models.BooleanField(default=False)),
                ('mobile', models.BooleanField(default=False)),
                ('web', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='veregood/brands/icon')),
                ('image', models.ImageField(blank=True, null=True, upload_to='veregood/brands/image')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.BigIntegerField(default=0)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='veregood/sub_category/icon')),
                ('image', models.ImageField(blank=True, null=True, upload_to='veregood/sub_category/image')),
                ('is_active', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child', to='veregood.category')),
            ],
            options={
                'verbose_name_plural': 'categories',
                'unique_together': {('slug', 'parent')},
            },
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('slug', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='veregood/brands/icon')),
                ('image', models.ImageField(blank=True, null=True, upload_to='veregood/brands/image')),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='MainCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='veregood/category/icon')),
                ('image', models.ImageField(blank=True, null=True, upload_to='veregood/category/image')),
                ('is_active', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_id', models.CharField(default=uuid.uuid4, max_length=255, primary_key=True, serialize=False, unique=True)),
                ('status', models.CharField(max_length=255)),
                ('amount_paid', models.IntegerField(default=0)),
                ('paid', models.BooleanField(default=False)),
                ('captured', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, max_length=1500, null=True)),
                ('sku', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='veregood/product/image/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='veregood/product/image/thumnail/')),
                ('short_description', models.TextField(blank=True, max_length=5500, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('rating', models.DecimalField(decimal_places=1, default=0.0, max_digits=3)),
                ('has_color', models.BooleanField(default=False)),
                ('has_variation', models.BooleanField(default=False)),
                ('product_type', models.CharField(choices=[('simple', 'simple'), ('variable', 'variable'), ('acution', 'acution'), ('quote', 'quote')], default='simple', max_length=255)),
                ('is_active', models.BooleanField(default=False)),
                ('in_stock', models.BooleanField(default=False)),
                ('quantity', models.BigIntegerField(default=0)),
                ('page_layout', models.CharField(choices=[('layout_1', 'Layout 1'), ('layout_2', 'Layout 2'), ('layout_3', 'Layout 3'), ('layout_4', 'Layout 4'), ('layout_5', 'Layout 5 - Supports 3D Sliders')], default='layout_1', max_length=100)),
                ('is_approved', models.BooleanField(default=False)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='veregood.brand')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_product', to='veregood.category')),
                ('main_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='main_category_product', to='veregood.maincategory')),
            ],
        ),
        migrations.CreateModel(
            name='STOREBANKACCOUNT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(blank=True, max_length=255, null=True)),
                ('account_number', models.CharField(blank=True, max_length=255, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=255, null=True)),
                ('bank_address', models.CharField(blank=True, max_length=255, null=True)),
                ('routing_number', models.CharField(blank=True, max_length=255, null=True)),
                ('iban', models.CharField(blank=True, max_length=255, null=True)),
                ('swift_code', models.CharField(blank=True, max_length=255, null=True)),
                ('ifsc_code', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='STOREKYC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_name', models.CharField(blank=True, max_length=255, null=True)),
                ('vendor_proof_number', models.CharField(blank=True, max_length=255, null=True)),
                ('vendor_proof', models.ImageField(blank=True, null=True, upload_to='profile/')),
            ],
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WishlistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='veregood.product')),
                ('wishlist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wishitem', to='veregood.wishlist')),
            ],
        ),
        migrations.CreateModel(
            name='VariationGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_price', models.BooleanField(default=False)),
                ('title', models.CharField(choices=[('color', 'color'), ('size', 'size'), ('weight', 'weight')], default='simple', max_length=100)),
                ('suffix', models.CharField(blank=True, max_length=100, null=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='varation_group', to='veregood.product')),
            ],
            options={
                'verbose_name': 'Variation Group',
            },
        ),
        migrations.CreateModel(
            name='Variation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='veregood/product/variation/image/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='veregood/product/image/variation/thumnail/')),
                ('text', models.CharField(blank=True, max_length=255, null=True)),
                ('value', models.CharField(blank=True, max_length=255, null=True)),
                ('sub_text', models.CharField(blank=True, max_length=255, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('is_active', models.BooleanField(default=False)),
                ('in_stock', models.BooleanField(default=False)),
                ('quantity', models.BigIntegerField(default=0)),
                ('variation_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_varation', to='veregood.variationgroup')),
            ],
            options={
                'verbose_name': 'Variation',
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_id', models.CharField(default=uuid.uuid4, max_length=255, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logo/')),
                ('store_name', models.CharField(blank=True, max_length=255, null=True)),
                ('store_describtion', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_mobile_number', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_email', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.TextField(blank=True, max_length=1000, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, verbose_name='Location')),
                ('location_name', models.CharField(blank=True, max_length=100, null=True)),
                ('gst_number', models.CharField(blank=True, max_length=100, null=True)),
                ('upi_id', models.CharField(blank=True, max_length=100, null=True)),
                ('rating', models.DecimalField(decimal_places=1, default=0.0, max_digits=10)),
                ('delivery_type', models.CharField(choices=[('self', 'self'), ('veregood', 'veregood')], default='self', max_length=100)),
                ('commision_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile/')),
                ('dob', models.DateField(blank=True, null=True)),
                ('age', models.IntegerField(default=18)),
                ('aadhar_number', models.CharField(blank=True, max_length=100, null=True)),
                ('pan_number', models.CharField(blank=True, max_length=100, null=True)),
                ('closed', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('store_setup', models.BooleanField(default=False)),
                ('is_approved', models.BooleanField(default=False)),
                ('kyc_verified', models.BooleanField(default=False)),
                ('payment_method_added', models.BooleanField(default=False)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProductTab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('content', tinymce.models.HTMLField()),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_tab', to='veregood.product')),
            ],
            options={
                'verbose_name': 'Tab',
            },
        ),
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.DecimalField(decimal_places=1, default=0.0, max_digits=3)),
                ('description', models.TextField(blank=True, max_length=1500, null=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_review', to='veregood.product')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Review',
            },
        ),
        migrations.CreateModel(
            name='ProductQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='veregood.product')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProductMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('keyword', models.TextField(blank=True, max_length=5500, null=True)),
                ('description', models.TextField(blank=True, max_length=5500, null=True)),
                ('product', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='veregood.product')),
            ],
            options={
                'verbose_name': 'Meta',
            },
        ),
        migrations.CreateModel(
            name='ProductListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_listing', to='veregood.collection')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='veregood.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='veregood/product/image/')),
                ('is_active', models.BooleanField(default=False)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_image', to='veregood.product')),
            ],
            options={
                'verbose_name': 'Image',
            },
        ),
        migrations.CreateModel(
            name='ProductGuide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', tinymce.models.HTMLField()),
                ('product', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='veregood.product')),
            ],
            options={
                'verbose_name': 'Guide',
            },
        ),
        migrations.CreateModel(
            name='ProductDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', tinymce.models.HTMLField()),
                ('product', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='veregood.product')),
            ],
            options={
                'verbose_name': 'Description',
            },
        ),
        migrations.CreateModel(
            name='ProductBid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid_amount', models.BigIntegerField(default=0)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='veregood.product')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='veregood.store'),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, verbose_name='Location')),
                ('total', models.BigIntegerField(default=0)),
                ('coupoun_discount', models.BigIntegerField(default=0)),
                ('delivery_charge', models.BigIntegerField(default=0)),
                ('tax', models.BigIntegerField(default=0)),
                ('final_total', models.BigIntegerField(default=0)),
                ('status', models.CharField(choices=[('onprocess', 'onprocess'), ('accepted', 'accepted'), ('picked', 'picked'), ('pending', 'pending'), ('abonded', 'abonded'), ('delivered', 'delivered'), ('recieved ', 'recieved'), ('on_the_way', 'on_the_way'), ('recived_by_delivery', 'recived_by_delivery'), ('delayed', 'delayed')], default='onprocess', max_length=100)),
                ('payment_type', models.CharField(choices=[('online', 'online'), ('cod', 'cod')], default='onprocess', max_length=100)),
                ('coupun_applied', models.BooleanField(default=False)),
                ('address', models.TextField(blank=True, max_length=1500, null=True)),
                ('customer_otp', models.CharField(default='7394', max_length=255)),
                ('delivery_status_notes', models.CharField(blank=True, max_length=255, null=True)),
                ('cart', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='veregood.cart')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_variation', models.BooleanField(default=False)),
                ('quantity', models.IntegerField(default=0)),
                ('line_total', models.IntegerField(default=0)),
                ('cart', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart_item', to='veregood.cart')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='veregood.product')),
                ('variation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='veregood.variation')),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flat_no', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, verbose_name='Location')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='useraddress', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
