# Generated by Django 3.2 on 2022-06-16 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veregood', '0002_alter_order_customer_otp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variation',
            name='addon_price',
        ),
        migrations.RemoveField(
            model_name='variation',
            name='group',
        ),
        migrations.RemoveField(
            model_name='variation',
            name='has_price',
        ),
        migrations.AddField(
            model_name='product',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='variation',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_otp',
            field=models.CharField(default='9734', max_length=255),
        ),
        migrations.DeleteModel(
            name='VariationGroup',
        ),
    ]
