# Generated by Django 3.2 on 2022-07-19 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veregood', '0003_alter_order_customer_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='draft',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_otp',
            field=models.CharField(default='8762', max_length=255),
        ),
    ]
