# Generated by Django 3.2 on 2022-06-16 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('veregood', '0004_auto_20220616_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='has_variation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='variation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='veregood.variation'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_otp',
            field=models.CharField(default='6685', max_length=255),
        ),
    ]
