# Generated by Django 3.2 on 2022-07-22 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('veregood', '0007_auto_20220721_1211'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='veregood/brands/icon')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_otp',
            field=models.CharField(default='9047', max_length=255),
        ),
        migrations.AlterField(
            model_name='variationgroup',
            name='title',
            field=models.CharField(choices=[('color', 'color'), ('size', 'size'), ('weight', 'weight'), ('packaging', 'packaging')], default='simple', max_length=100),
        ),
        migrations.AddField(
            model_name='collection',
            name='collection_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='veregood.collectiongroup'),
        ),
    ]
