# Generated by Django 3.2 on 2022-06-17 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veregood', '0008_auto_20220616_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='customer_otp',
            field=models.CharField(default='5069', max_length=255),
        ),
    ]
