# Generated by Django 3.2.8 on 2022-05-16 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_vendor'),
        ('veregood', '0009_auto_20220516_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='customer_otp',
            field=models.CharField(default='5017', max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.vendor'),
        ),
        migrations.DeleteModel(
            name='Vendor',
        ),
    ]
