# Generated by Django 3.2 on 2022-07-26 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veregood', '0010_alter_order_customer_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='explore',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='veregood/explore/images'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_otp',
            field=models.CharField(default='2890', max_length=255),
        ),
    ]
