# Generated by Django 3.2.8 on 2022-05-16 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veregood', '0011_auto_20220516_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='customer_otp',
            field=models.CharField(default='5991', max_length=255),
        ),
    ]
