# Generated by Django 3.2 on 2022-07-26 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veregood', '0012_auto_20220726_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='customer_otp',
            field=models.CharField(default='7506', max_length=255),
        ),
    ]
