# Generated by Django 3.2 on 2022-06-17 08:51

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('veregood', '0013_alter_order_customer_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=tinymce.models.HTMLField(default='hi'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_otp',
            field=models.CharField(default='1219', max_length=255),
        ),
    ]
