# Generated by Django 3.2.8 on 2022-05-16 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veregood', '0013_auto_20220516_1551'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='veregood/banner/image/')),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_otp',
            field=models.CharField(default='4729', max_length=255),
        ),
    ]
