# Generated by Django 3.2 on 2022-07-26 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('veregood', '0014_auto_20220726_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='collection_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='collections', to='veregood.collectiongroup'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_otp',
            field=models.CharField(default='9425', max_length=255),
        ),
    ]
