# Generated by Django 3.2 on 2022-06-17 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veregood', '0014_auto_20220617_0851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='customer_otp',
            field=models.CharField(default='8198', max_length=255),
        ),
    ]
