# Generated by Django 3.2 on 2022-07-26 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veregood', '0015_auto_20220726_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='customer_otp',
            field=models.CharField(default='7046', max_length=255),
        ),
    ]
