# Generated by Django 3.2 on 2022-07-26 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veregood', '0017_alter_order_customer_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectiongroup',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='explore',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_otp',
            field=models.CharField(default='6043', max_length=255),
        ),
    ]
