# Generated by Django 3.2 on 2022-06-19 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veregood', '0018_alter_order_customer_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='store',
            name='kyc_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='store',
            name='payment_method_added',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='store',
            name='store_setup',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='variation',
            name='has_price',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_otp',
            field=models.CharField(default='7507', max_length=255),
        ),
    ]
