# Generated by Django 3.2 on 2022-08-02 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veregood', '0019_auto_20220802_0454'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_otp',
            field=models.CharField(default='1756', max_length=255),
        ),
    ]
