# Generated by Django 3.2 on 2022-06-19 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('veregood', '0020_auto_20220619_1832'),
    ]

    operations = [
        migrations.AddField(
            model_name='variation',
            name='variation_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_varation', to='veregood.variationgroup'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_otp',
            field=models.CharField(default='1691', max_length=255),
        ),
    ]
