# Generated by Django 3.2 on 2022-08-04 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veregood', '0020_auto_20220802_0455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='customer_otp',
            field=models.CharField(default='5943', max_length=255),
        ),
    ]
