# Generated by Django 3.2 on 2022-08-04 05:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0001_initial'),
        ('currency', '0001_initial'),
        ('veregood', '0021_alter_order_customer_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='available_regions',
            field=models.ManyToManyField(blank=True, to='country.Country'),
        ),
        migrations.AddField(
            model_name='store',
            name='base_currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='currency.currency'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_otp',
            field=models.CharField(default='4748', max_length=255),
        ),
    ]
