# Generated by Django 3.2 on 2022-06-19 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veregood', '0021_auto_20220619_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='customer_otp',
            field=models.CharField(default='9393', max_length=255),
        ),
    ]
