# Generated by Django 3.2 on 2022-06-19 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veregood', '0022_alter_order_customer_otp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variation',
            name='product',
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_otp',
            field=models.CharField(default='8496', max_length=255),
        ),
    ]
