# Generated by Django 3.2 on 2022-06-19 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veregood', '0023_auto_20220619_1949'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variation',
            name='has_price',
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_otp',
            field=models.CharField(default='9310', max_length=255),
        ),
    ]
