# Generated by Django 3.2 on 2022-08-26 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veregood', '0024_auto_20220826_0916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='customer_otp',
            field=models.CharField(default='2272', max_length=255),
        ),
    ]
