# Generated by Django 3.2 on 2022-06-19 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veregood', '0024_auto_20220619_2000'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='page_layout',
            field=models.CharField(choices=[('layout_1', 'Layout 1 - Supports 3D Sliders'), ('layout_2', 'Layout 2'), ('layout_3', 'Layout 3'), ('layout_4', 'Layout 4'), ('layout_5', 'Layout 5')], default='layout_1', max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_otp',
            field=models.CharField(default='7865', max_length=255),
        ),
    ]
