# Generated by Django 3.2 on 2022-08-30 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veregood', '0026_auto_20220826_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='sub_total',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_otp',
            field=models.CharField(default='9568', max_length=255),
        ),
    ]
