# Generated by Django 3.2 on 2022-06-20 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veregood', '0028_auto_20220619_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='customer_otp',
            field=models.CharField(default='4773', max_length=255),
        ),
    ]
