# Generated by Django 3.2.12 on 2022-12-30 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veregood', '0028_auto_20221227_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='customer_otp',
            field=models.CharField(default='1069', max_length=255),
        ),
    ]
