# Generated by Django 3.2 on 2022-06-20 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veregood', '0030_auto_20220620_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='customer_otp',
            field=models.CharField(default='8108', max_length=255),
        ),
    ]
