# Generated by Django 3.2 on 2022-06-20 10:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('veregood', '0032_auto_20220620_1026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productquote',
            name='bid_amount',
        ),
        migrations.AddField(
            model_name='productquote',
            name='content',
            field=models.TextField(default='aa'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_otp',
            field=models.CharField(default='3227', max_length=255),
        ),
        migrations.CreateModel(
            name='ProductBid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid_amount', models.BigIntegerField(default=0)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='veregood.product')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
