# Generated by Django 3.2.12 on 2023-01-03 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veregood', '0033_alter_order_customer_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='customer_otp',
            field=models.CharField(default='9793', max_length=255),
        ),
    ]
