# Generated by Django 3.2 on 2022-06-20 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veregood', '0033_auto_20220620_1028'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productdescription',
            options={'verbose_name': 'Description'},
        ),
        migrations.AlterModelOptions(
            name='productguide',
            options={'verbose_name': 'Guide'},
        ),
        migrations.AlterModelOptions(
            name='productimage',
            options={'verbose_name': 'Image'},
        ),
        migrations.AlterModelOptions(
            name='productmeta',
            options={'verbose_name': 'Meta'},
        ),
        migrations.AlterModelOptions(
            name='productreview',
            options={'verbose_name': 'Review'},
        ),
        migrations.AlterModelOptions(
            name='variation',
            options={'verbose_name': 'Variation'},
        ),
        migrations.AlterModelOptions(
            name='variationgroup',
            options={'verbose_name': 'Variation Group'},
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_otp',
            field=models.CharField(default='1513', max_length=255),
        ),
    ]
