# Generated by Django 3.2 on 2022-06-21 14:46

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0004_auto_20220621_1446'),
        ('veregood', '0034_auto_20220620_1032'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tag',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_otp',
            field=models.CharField(default='6523', max_length=255),
        ),
    ]
