# Generated by Django 3.2 on 2022-06-21 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veregood', '0035_auto_20220621_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='customer_otp',
            field=models.CharField(default='6484', max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='page_layout',
            field=models.CharField(choices=[('layout_1', 'Layout 1'), ('layout_2', 'Layout 2'), ('layout_3', 'Layout 3'), ('layout_4', 'Layout 4'), ('layout_5', 'Layout 5 - Supports 3D Sliders')], default='layout_1', max_length=100),
        ),
    ]
