# Generated by Django 3.2.12 on 2023-01-10 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veregood', '0036_auto_20230110_0911'),
    ]

    operations = [
        migrations.AddField(
            model_name='websitelogs',
            name='current_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_otp',
            field=models.CharField(default='7176', max_length=255),
        ),
    ]
