# Generated by Django 3.2.12 on 2023-01-10 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veregood', '0037_auto_20230110_0915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='customer_otp',
            field=models.CharField(default='3987', max_length=255),
        ),
        migrations.AlterField(
            model_name='websitelogs',
            name='date',
            field=models.DateField(blank=True, null=True, unique=True),
        ),
    ]
