# Generated by Django 3.2 on 2022-06-21 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veregood', '0037_auto_20220621_1823'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producttab',
            options={'verbose_name': 'Tab'},
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_otp',
            field=models.CharField(default='2732', max_length=255),
        ),
    ]
