# Generated by Django 3.2.12 on 2023-03-01 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('veregood', '0038_auto_20230110_0921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='customer_otp',
            field=models.CharField(default='3380', max_length=255),
        ),
        migrations.AlterField(
            model_name='productdescription',
            name='product',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='description', to='veregood.product'),
        ),
    ]
