# Generated by Django 3.2 on 2022-06-21 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veregood', '0039_alter_order_customer_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='customer_otp',
            field=models.CharField(default='8065', max_length=255),
        ),
        migrations.AlterField(
            model_name='producttab',
            name='content',
            field=models.TextField(),
        ),
    ]
