# Generated by Django 3.2 on 2022-06-21 19:49

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('veregood', '0040_auto_20220621_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='customer_otp',
            field=models.CharField(default='6647', max_length=255),
        ),
        migrations.AlterField(
            model_name='producttab',
            name='content',
            field=tinymce.models.HTMLField(),
        ),
    ]
