# Generated by Django 3.2 on 2022-06-21 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veregood', '0041_auto_20220621_1949'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='tag',
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_otp',
            field=models.CharField(default='8519', max_length=255),
        ),
    ]
